### PR TITLE
Support Angular 1.4.x

### PR DESCRIPTION
**Pull request by kitak**
Angular 1.4.0 has been released.
So, I fixed package.json.

### CODE REVIEW

**Comment by bendrucker** [comment]
Happy to merge but don't specify the range this way. `>= 1.3 < 1.5` for the peer, and use `~1.4.0` and not a range for the devDeps.

**Comment by kitak** [comment]
Thank you for your comment.
I fixed the range specification. Could you review it ?

**Comment by bendrucker** [comment]
Please squash the commits and I'll merge

**Comment by kitak** [comment]
I squashed my commits into one.

**Pull request merged**
