### PR TITLE
specify dependencies correctly

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by bendrucker** [comment]
This is partially correct. The devDep change is correct, changing the peer range is wrong. Changing transforms to devDeps is also wrong as they need to be installed everywhere.

**Comment by bendrucker** [comment]
Wait never mind it was originally a devDep so all of these are wrong. Feel free to ask for clarification if I need to elaborate on why.

**Comment by bendrucker** [comment]
Thanks for the PR though!

**Comment by lookfirst** [comment]
I see deps as being what your source code depends on. Your source code doesn't depend on things to do transforms.

As for the peerdep, it seems like if your code depends on angular 1.4.x, then your peers should as well. But I can certainly be convinced otherwise.

**Comment by bendrucker** [comment]
It's not a philosophical issue. When you `npm install angular-credit-cards` and are using Browserify, you need those transforms to be installed for things to work. 

This is gonna be moot anyway because I'm going to eliminate the need to use Babel.

> it seems like if your code depends on angular 1.4.x

It doesn't though. I 1.3+.

**Comment by lookfirst** [comment]
Sounds like more of an issue with browserify than with the dependencies declarations. Basically, you're saying that your code depends on browserify, which seems wrong, since it doesn't. Your build depends on browserify, which is a different issue.

**Comment by bendrucker** [comment]
> It's not a philosophical issue

https://github.com/substack/node-browserify#browserifytransform

**Comment by lookfirst** [comment]
Lame

**Pull request closed without merging**
