### PR TITLE
Set expMonth invalid if it is past month of currenct year

### PR DESCRIPTION
**Pull request by Nekle**

### CODE REVIEW

**Comment by bendrucker** [comment]
Sorry but this isn't something I'm interested in including. The parent component (`ccExp`) manages the shared state (month + year) and then each subcomponent (`ccExpMonth` and `ccExpYear`) handles its own logic.

**Comment by Nekle** [comment]
it dose not set month model invalid, if I give 09/2015 
can you fix this please :)

**Comment by bendrucker** [comment]
Yes that's intended. If you need to know if the month/year pair is invalid you use `ccExp`. `09` is a perfectly valid credit card month entry and `ccExpMonth` should not be invalid if it receives that input.

**Comment by Nekle** [comment]
thank you, but from `ccExp`, unable to know it is because month or year.
Year has been validated if it is past, why not validate month too.

**Comment by bendrucker** [comment]
Final answer is that I'm not going to include this in the library. I definitely encourage you to publish your own directive. The [engine](https://github.com/bendrucker/creditcards) is 100% independent so you can do additional custom validation. I don't think this is a common enough want to merit in the lib.

**Pull request closed without merging**
